// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXFH2gJ7yBxTWQzJZCst2MAxfX-BTb804',
    appId: '1:979391535310:web:65b4d19ee6defed7c8989f',
    messagingSenderId: '979391535310',
    projectId: 'shopapp-1010',
    authDomain: 'shopapp-1010.firebaseapp.com',
    storageBucket: 'shopapp-1010.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBl12zLyqWi7ba2jbpV61QCcq8bzkH5FvM',
    appId: '1:979391535310:android:0394d133f0d85c95c8989f',
    messagingSenderId: '979391535310',
    projectId: 'shopapp-1010',
    storageBucket: 'shopapp-1010.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkDu9sXtOFYQiJ8nfTjyBC7w318i4gf9E',
    appId: '1:979391535310:ios:ac6eca042d5ea9a0c8989f',
    messagingSenderId: '979391535310',
    projectId: 'shopapp-1010',
    storageBucket: 'shopapp-1010.firebasestorage.app',
    iosBundleId: 'com.example.shoppingapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkDu9sXtOFYQiJ8nfTjyBC7w318i4gf9E',
    appId: '1:979391535310:ios:ac6eca042d5ea9a0c8989f',
    messagingSenderId: '979391535310',
    projectId: 'shopapp-1010',
    storageBucket: 'shopapp-1010.firebasestorage.app',
    iosBundleId: 'com.example.shoppingapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXFH2gJ7yBxTWQzJZCst2MAxfX-BTb804',
    appId: '1:979391535310:web:16217b77cb1c149ec8989f',
    messagingSenderId: '979391535310',
    projectId: 'shopapp-1010',
    authDomain: 'shopapp-1010.firebaseapp.com',
    storageBucket: 'shopapp-1010.firebasestorage.app',
  );
}
