// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzPz6vLwJ5iWx7A_Ksec62EGTmm-Epj10',
    appId: '1:610694894570:web:e2a55c375250f076089893',
    messagingSenderId: '610694894570',
    projectId: 'spotify250025',
    authDomain: 'spotify250025.firebaseapp.com',
    storageBucket: 'spotify250025.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHoycNg9qhCgViaprI9RXasefN-sr-18o',
    appId: '1:610694894570:android:1972e2f97299da43089893',
    messagingSenderId: '610694894570',
    projectId: 'spotify250025',
    storageBucket: 'spotify250025.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrJY-iaNdo_YrDckXBCngu4Q4WSUyy3aQ',
    appId: '1:610694894570:ios:5e8879bf20ac330b089893',
    messagingSenderId: '610694894570',
    projectId: 'spotify250025',
    storageBucket: 'spotify250025.appspot.com',
    iosBundleId: 'com.example.spotify2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrJY-iaNdo_YrDckXBCngu4Q4WSUyy3aQ',
    appId: '1:610694894570:ios:5e8879bf20ac330b089893',
    messagingSenderId: '610694894570',
    projectId: 'spotify250025',
    storageBucket: 'spotify250025.appspot.com',
    iosBundleId: 'com.example.spotify2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAzPz6vLwJ5iWx7A_Ksec62EGTmm-Epj10',
    appId: '1:610694894570:web:a3a14f9108c07095089893',
    messagingSenderId: '610694894570',
    projectId: 'spotify250025',
    authDomain: 'spotify250025.firebaseapp.com',
    storageBucket: 'spotify250025.appspot.com',
  );
}
